### PR TITLE
fix: support build targets with different name than its path filename

### PR DESCRIPTION
**Pull request by williamboman**
I ran into some errors when upgrading to `4.0.0-beta.0`. I was able to
boil it down (I think) to the fact that I have multiple API paths that
have the same entrypath filename (e.g. `/api/user/[id].rs` and
`/api/group/[id].rs`). What happens currently is that this runtime
will try to build these binaries by their filename (e.g. `_id_`), but
this introduces ambiguity because only one of these build targets can
occupy that name.

I feel like I might've missed something, but figured I'd open a PR
anyway, hope you don't mind!

### CODE REVIEW

**Comment by williamboman** [comment]
I've been unable to actually test this out so far, and the test case fails (I assume because it pulls the runtime from `npm` instead of locally?). Any pointers on how to actually test this locally in a vercel project would be appreciated!

~edit: Actually scratch that. `npm link` seemed to do the trick for testing it in a different vercel project. Does indeed fix my issues!~

~edit2: nvm I had changed Cargo.toml to be in a functioning state for the particular endpoint I was testing~

edit3: I've now been able to test this properly locally (pushed another commit). Still not sure how to make the test not pull the runtime from npm (it seems to override `npm link` every time)

**Comment by ecklf** [comment]
> hope you don't mind!

Wow didn't expect to receive feedback and even a fix so quickly. Any help is more than welcome!

> Any pointers on how to actually test this locally in a vercel project would be appreciated!

Good point. The [old tests](https://github.com/vercel-community/rust/blob/a9495a0f0d882a36ea165f1629fcc79c30bc3108/test/fixtures/01-include-files/test.vercel.json) used `builds` in `vercel.json`, however this usage is currently broken in the latest Vercel CLI. I could only get that to work for `vercel@28.2.5` and below, hence I dropped it. I think we'd want to use https://github.com/TooTallNate/vercel-dev-builder to get past the package publishing restrictions. I'll look into migrating to that one instead.

In the long term we want to roll out a solution where handlers will be deployed as one lambda with internal routing, which would get rid of the `[[bin]]` annotating annoyance. This fix is definitely the way to go for now. Thank you.

**Review by ecklf — APPROVED** [review]

**Comment by ecklf** [comment]
Published [4.0.0.beta.1](https://github.com/vercel-community/rust/commit/fda52d88e1cda8675cd98b40c7283f224c71a488)

**Comment by williamboman** [comment]
> Published [4.0.0.beta.1](https://github.com/vercel-community/rust/commit/fda52d88e1cda8675cd98b40c7283f224c71a488)

Awesome, thanks for the quick response! https://github.com/mason-org/mason-registry-api/pull/22 happily deployed now :)

**Comment by ecklf** [comment]
Nice! Can we reach out to you regarding feedback on merged handlers?

**Comment by williamboman** [comment]
> Nice! Can we reach out to you regarding feedback on merged handlers?

Sure!

**Comment by ecklf** [comment]
> > Nice! Can we reach out to you regarding feedback on merged handlers?
> 
> Sure!

Thoughts on https://github.com/vercel-community/rust/pull/86? This should get rid of https://github.com/mason-org/mason-registry-api/blob/main/Cargo.toml#L25-L115.

**Pull request merged**
