### PR TITLE
upgrade lambda_runtime crate dependencies & add async handler fn support

### LINKED ISSUE #46: Update all dependencies to their latest versions

### PR DESCRIPTION
**Pull request by hanabi1224**
This PR includes below changes, please let me know ur feedback, thanks!

- Add async handler fn support
- Make tokio an optional dependency behind feature `runtime` (default on)
- Upgrade tokio to 1.14
- Upgrade http to 0.2
- Upgrade lambda_runtime to 0.4
- Upgrade to rust 2021

The API change in this PR should keep backward compatibility. All style changes come from ```cargo fmt```

Resolves https://github.com/vercel-community/rust/issues/46  https://github.com/vercel-community/rust/issues/20

### CODE REVIEW

**Comment by frencojobs** [comment]
Could normal and async stuff be in separate files (e.g `sync.rs` and `async.rs`), since they're pretty much distinct from what I see in the implementation?

Also, why do we need this?
```toml
# Cargo.toml
[dev-dependencies]
anyhow = "1"
tokio = "1.12"
```

**Comment by ngryman** [comment]
Async should really be a first-class citizen.
Is there anything we could do to move this forward?

**Comment by hanabi1224** [comment]
It will be great if this PR can get reviewed soon, before it's merged and published, ppl can point the crate to my fork

```toml
# Cargo.toml
vercel_lambda = {git = "https://github.com/hanabi1224/rust", branch = "update_lambda_runtime_deps"}
```

**Comment by ArthurianX** [comment]
Is this abandoned ?

**Comment by ecklf** [comment]
Closing this in favor of https://github.com/vercel-community/rust/pull/80/files

**Pull request closed without merging**
