### PR TITLE
feat: Transparently support pre-configured binaries

### PR DESCRIPTION
**Pull request by connec**
In the event that a binary is already defined for the target entrypoint in `Cargo.toml`, the associated name is used without rewriting the `Cargo.toml` file. This approach may be preferable with some development environments that require binaries to be defined in order to perform builds, etc.

### CODE REVIEW

**Comment by mike-engel** [comment]
Hi @connec would you mind rebasing this?

**Comment by connec** [comment]
Hi @mike-engel, very long overdue but I've rebased this now! I also added a test, which like all the tests fails on master, but it works when combined with #38.

**Comment by connec** [comment]
I realised `entrypointPath` must have become absolute at some point, so I've updated this to deal with that.

**Comment by mike-engel** [comment]
Thanks for your patience here @connec!

**Pull request merged**
