### PR TITLE
changing ZEIT to Vercel

### PR DESCRIPTION
**Pull request by nico-bachner**
Issue #33 : ZEIT has rebranded as Vercel

This PR should ideally **not** be merged until sure that nothing will be broken (that could take a while)

### CODE REVIEW

**Review by mike-engel — APPROVED** [review]

**Comment by mike-engel** [comment]
Let's go ahead and also change any code that needs to change as well. That includes `package.json`

**Comment by nico-bachner** [comment]
`package.json` is done.

Will tackle the rest now

**Comment by nico-bachner** [comment]
What exactly is the purpose of `Cargo.toml` in the project? I'm not sure I quite understand. 
Shouldn't it have the information of the project - `vercel-rust` (prev. `now-rust`) instead of `now-lambda`?

**Review by mike-engel — APPROVED** [review]

**Comment by mike-engel** [comment]
> What exactly is the purpose of Cargo.toml in the project? I'm not sure I quite understand.
Shouldn't it have the information of the project - vercel-rust (prev. now-rust) instead of now-lambda?

Good question! There is actually a [crate published from this repo](https://crates.io/crates/now_lambda), which folks should use in their rust code. I'll have to update that as well once I switch everything over

**Comment by nico-bachner** [comment]
So is the final goal to make the crate resemble the npm package?

**Comment by mike-engel** [comment]
In name, yes. In functionality, no. `now_lambda` acts as a rust component to the entire `vercel-rust` system, which adds some extra functions and types to allow rust code to run well on vercel

**Comment by nico-bachner** [comment]
Ah I see. Thanks.

**Review by mike-engel — APPROVED** [review]

**Pull request merged**
